### ISSUE TITLE
tour-step doesn't works with ngFor

### ISSUE THREAD

**Issue by guilhermejcgois** [miraxes/angular-custom-tour#7] opened 2018-03-12 20:04 UTC
Why do u get {selector, order} from DOM node [here](https://github.com/miraxes/angular-custom-tour/blob/master/src/hint.service.ts#L147) instead from [anchors](https://github.com/miraxes/angular-custom-tour/blob/master/src/hint.service.ts#L17)? We can't use a ngfor like that:
```
<tour-step *ngFor="let item of items" [order]="item.order" [selector]="item.selector" [position]="item.position">
  <tour-step-item [items]="items" [order]="item.order" [current]="currentStep" (reduce)="reduce($event)"></tour-step-item>
</tour-step>
```

**Comment by miraxes** [comment] 2018-03-12 21:48
Thanks for using it, my friend! 
I don't really remember the reason >_< but that was something about avoid bugs for missing steps, and double checking everything...

So the problem is when using ngFor [selector] is missing on attrs
Here is workaround for you.

`<tour-step *ngFor="let item of items" [attr.selector]="item.selector" [selector]="item.selector" ....>
   ...
</tour-step>`
[selector] -> is for navigating on steps
 [attr.selector] -> is for initialize

Let me know if it working for you, please!

**Comment by miraxes** [comment] 2018-03-13 15:35
Well, closing this one.

You can suggest changes if you find better way of service initialize.

**Closed by miraxes** 2018-03-13 15:35 UTC

**Comment by guilhermejcgois** [comment] 2018-03-14 14:20
Hey, sorry for the delay... Your workaround works! I was thinking about the implementation, seems to me a little confuse get `order` and `selector` from DOM instead using the `anchors` property, can't be dangerous if both desynchronizes?
